routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/search','HomeController@searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@autocomplete')->name('autocomplete');
// Hotel
Route::get('/all-hotel','HomeController@all_hotel')->name('hotel');
// Hotel Details
Route::get('/hotel/{id}/{slug}','HomeController@hotel')->name('hotel-details');
// Room
Route::get('/room/{id}/{slug}','HomeController@room')->name('room');
// Room Booking
Route::post('/room_booking','HomeController@roomBooking')->name('booking');
Route::post('/one-room-booking','HomeController@oneroomBooking')->name('one_booking');
// Admin Route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'admin','middleware' => ['auth','admin']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Owner
    Route::resource('owner','OwnerController');
    // Division
    Route::resource('division','DivisionController');
    // Zillas
    Route::resource('zilla','ZillaController');
    // Hotel
    Route::resource('hotel','HotelController');
    // Facilities
    Route::resource('facilities','FacilitiesController');

    Route::get('/district','HotelController@getDistrict');
   // Room
    Route::resource('room','RoomController');
    // Booking
    Route::resource('booking','BookingController');
    Route::get('/reject','BookingController@bookingReject')->name('booking.reject');



    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// Owner Route
Route::group(['as' =>'owner.','prefix'=>'owner','namespace'=>'owner','middleware' => ['auth','owner']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Room
    Route::resource('room','RoomController');
    Route::post('/room-free','RoomController@unbooking')->name('room-free');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// User Route
Route::group(['as' =>'user.','prefix'=>'user','namespace'=>'user','middleware' => ['auth','user']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});

app/Http/Controllers/Admin/FacilitiesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Facilities;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FacilitiesController extends Controller
{

    public function index()
    {
        $facilities = Facilities::latest()->get();
        return view('admin.facilities.index',compact('facilities'));
    }


    public function create()
    {
        //
    }

    public function store(Request $request)
    {

        $facilities = $request->facilities;
        foreach ($facilities as $facility)
        {
            DB::table('facilities')->insert(array(
                'name'   => $facility
            ));
        }
        Toastr::success('Facilities Added Successfully','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.facilities.index');
    }


    public function show(Facilities $facilities)
    {
        //
    }


    public function edit(Facilities $facilities)
    {
        //
    }

    public function update(Request $request)
    {
        $facilities_id  = $request->id;
        $name           = $request->faciname;
        $facilities     = Facilities::where('id',$facilities_id)->first();
        $facilities->name = $name;
        $facilities->save();

        Toastr::success('Facilities Successfully Updated','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.facilities.index');
    }

    public function destroy($id)
    {
        $facilities = Facilities::where('id',$id)->first();
        $facilities->delete();
        Toastr::success('Facilities Successfully Deleted','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.facilities.index');
    }
}

resources/views/admin/facilities/index.blade.php
@extends('layouts.backend.app')
@section('title','Facilities List')
@push('css')

@endpush

@section('content')
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Facilities List</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{{ route('admin.dashboard') }}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li><a class="parent-item" href="{{ route('admin.facilities.index') }}">Facilities</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Facilities List</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-box">
                                        <div class="card-head">
                                            <header>Facilities List <span class="badge bg-info">{{ $facilities->count() }}</span></header>

                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                                <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                                                <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6 col-6">
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addNew">
                                                            Add New <i class="fa fa-plus"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-sm-6 col-6">

                                                </div>
                                            </div>
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column valign-middle" id="example4">
                                                    <thead>
                                                    <tr class="center">
                                                        <th>#</th>
                                                        <th>Name</th>
                                                        <th>Action </th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    @foreach($facilities as $key=>$faci)
                                                        <tr class="odd gradeX">

                                                            <td>{{ $key+1 }}</td>
                                                            <td class="center">{{ $faci->name }}</td>
                                                            <td class="center">
                                                            <button data-toggle="modal" data-target="#Edit" data-id="{{ $faci->id }}" data-name="{{ $faci->name}} " class="btn btn-info btn-xs"> <i class="icon-note" id="edit_icon"></i></button>



                                                                <button class="btn btn-danger btn-xs"  type="button" onclick="deleteHotel({{ $faci->id }})">
                                                                    <i class="fa fa-trash" id="del_icon"></i>
                                                                </button>
                                                                <form id="delete-form-{{ $faci->id }}" action="{{ route('admin.facilities.destroy',$faci->id) }}" method="POST" style="display: none;">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                </form>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Add Hotel Modal -->
    <div class="modal fade" id="addNew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.facilities.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="modal-body">
                            <div class="row">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th><a href="#" class="addRow"><i class="fa fa-plus" aria-hidden="true"></i> Add New</a></th>
                                    </tr>
                                    </thead>
                                    <tbody id="customtbl">
                                    <tr>
                                        <td><input type="text" name="facilities[]" class="form-control" required=""></td>
                                        <td><button type="button" class="btn btn-danger btn-sm btn-rect" onclick="javascript:remove25(this);">Close</button></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Edit Employee Modal -->
    <div class="modal fade" id="Edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edfaciacilities</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.facilities.update',$faci->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="modal-body">
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div  class="form-group">
                                        <label for="facName">Name</label>
                                        <input type="text" name="faciname" id="facName" class="form-control"/>
                                        <input type="hidden" name="id" id="Fid" class="form-control"/>
                                    </div>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('js')

    <script type="text/javascript">
        $('#Edit').on('show.bs.modal', function (event) {
            var button          = $(event.relatedTarget);
            var faciId          = button.data('id');
            var facilName       = button.data('name');


            var modal = $(this);

            modal.find('.modal-body #Fid').val(faciId);
            modal.find('.modal-body #facName').val(facilName);




        });
        function deleteHotel(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }


    </script>
    <script type="text/javascript">
        var i75 = 0;
        $('.addRow').on('click',function(){
            addRow();
        });
        function addRow()
        {
            i75++;
            var tr='<tr>'+
                '<td><input type="text" name="facilities[]" class="form-control" required=""></td>'+
                '<td><button type=\'button\' class=\'btn btn-danger btn-sm btn-rect\' onclick=\'javascript:remove25(this);\'>Close</button></td>'+
                '</tr>';
            $('#customtbl').append(tr);
        };

        function remove25(index){
            console.log("hello");
            $(index).parent().parent().remove();
        }
    </script>

@endpush