routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/search','HomeController@searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@autocomplete')->name('autocomplete');
// Hotel
Route::get('/all-hotel','HomeController@all_hotel')->name('hotel');
// Hotel Details
Route::get('/hotel/{id}/{slug}','HomeController@hotel')->name('hotel-details');
// Room
Route::get('/room/{id}/{slug}','HomeController@room')->name('room');
// Room Booking
Route::post('/room_booking','HomeController@roomBooking')->name('booking');
Route::post('/one-room-booking','HomeController@oneroomBooking')->name('one_booking');
// Admin Route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'admin','middleware' => ['auth','admin']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Owner
    Route::resource('owner','OwnerController');
    // Division
    Route::resource('division','DivisionController');
    // Zillas
    Route::resource('zilla','ZillaController');
    // Hotel
    Route::resource('hotel','HotelController');
    // Facilities
    Route::resource('facilities','FacilitiesController');

    Route::get('/district','HotelController@getDistrict');
   // Room
    Route::resource('room','RoomController');
    // Booking
    Route::resource('booking','BookingController');
    Route::get('/reject','BookingController@bookingReject')->name('booking.reject');



    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// Owner Route
Route::group(['as' =>'owner.','prefix'=>'owner','namespace'=>'owner','middleware' => ['auth','owner']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Room
    Route::resource('room','RoomController');
    Route::post('/room-free','RoomController@unbooking')->name('room-free');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// User Route
Route::group(['as' =>'user.','prefix'=>'user','namespace'=>'user','middleware' => ['auth','user']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});

resources/views/layouts/backend/partial/header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">
        <!-- logo start -->
        <div class="page-logo">
            <a href="#">
                <span class="logo-icon material-icons fa-rotate-45">school</span>
                <span class="logo-default" >HBS</span> </a>
        </div>
        <!-- logo end -->
        <ul class="nav navbar-nav navbar-left in">
            <li><a href="#" class="menu-toggler sidebar-toggler"><i class="icon-menu"></i></a></li>
        </ul>
        <!-- start mobile menu -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- end mobile menu -->
        <!-- start header menu -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

                <!-- start manage user dropdown -->
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle " src=" {{ asset('storage/profile/'.Auth::user()->image) }}" />
                        <span class="username username-hide-on-mobile"> {{ Auth::user()->name }} </span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        @if(Request::is('admin*'))

                            <li>
                                <a href="{{ route('admin.profile.view',Auth::id()) }}">
                                    <i class="icon-user"></i> Profile </a>
                            </li>
                            <li>
                                <a href="{{ route('admin.profile.index') }}">
                                    <i class="icon-settings"></i> Settings
                                </a>
                            </li>

                        @elseif(Request::is('owner*'))
                            <li>
                                <a href="{{ route('owner.profile.view',Auth::id()) }}">
                                    <i class="icon-user"></i> Profile </a>
                            </li>
                            <li>
                                <a href="{{ route('owner.profile.index') }}">
                                    <i class="icon-settings"></i> Settings
                                </a>
                            </li>
                        @else
                            <li>
                                <a href="{{ route('user.profile.view',Auth::id()) }}">
                                    <i class="icon-user"></i> Profile </a>
                            </li>
                            <li>
                                <a href="{{ route('user.profile.index') }}">
                                    <i class="icon-settings"></i> Settings
                                </a>
                            </li>
                        @endif
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                <i class="icon-logout"></i> Log Out </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
                <!-- end manage user dropdown -->
            </ul>
        </div>
    </div>
</div>

resources/views/layouts/backend/partial/sidebar.blade.php
<!-- start sidebar menu -->
<div class="sidebar-container">
    <div class="sidemenu-container navbar-collapse collapse fixed-menu">
        <div id="remove-scroll" class="left-sidemenu">
            <ul class="sidemenu  page-header-fixed slimscroll-style" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                <li class="sidebar-toggler-wrapper hide">
                    <div class="sidebar-toggler">
                        <span></span>
                    </div>
                </li>
                <li class="sidebar-user-panel">
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src=" {{ asset('storage/profile/'.Auth::user()->image) }}" class="img-circle user-img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p> {{ Auth::user()->name }}</p>
                            <a href="#"><i class="fa fa-circle user-online"></i><span class="txtOnline"> Online</span></a>
                        </div>
                    </div>
                </li>
                @if(Request::is('admin*'))
                    <li class="nav-item {{ Request::is('admin/dashboard') ? 'active':'' }}">
                        <a href="{{ route('admin.dashboard') }}" class="nav-link nav-toggle"> <i class="material-icons">dashboard</i>
                            <span class="title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item {{ Request::is('admin/owner*') ? 'active':'' }}">
                        <a href="{{ route('admin.owner.index') }}" class="nav-link nav-toggle"> <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            <span class="title">Hotel Owners</span>
                        </a>
                    </li>
{{--                    <li class="nav-item {{ Request::is('admin/division*') ? 'active':'' }}">--}}
{{--                        <a href="{{ route('admin.division.index') }}" class="nav-link nav-toggle"> <i class="fa fa-bars" aria-hidden="true"></i>--}}
{{--                            <span class="title">Divisions</span>--}}
{{--                        </a>--}}
{{--                    </li>--}}
{{--                    <li class="nav-item {{ Request::is('admin/zilla*') ? 'active':'' }}">--}}
{{--                        <a href="{{ route('admin.zilla.index') }}" class="nav-link nav-toggle"> <i class="fa fa-sitemap" aria-hidden="true"></i>--}}
{{--                            <span class="title">Zilla</span>--}}
{{--                        </a>--}}
{{--                    </li>--}}
                    <li class="nav-item {{ Request::is('admin/hotel*') ? 'active':'' }}">
                        <a href="{{ route('admin.hotel.index') }}" class="nav-link nav-toggle"> <i class="fa fa-h-square" aria-hidden="true"></i>
                            <span class="title">Hotels</span>
                        </a>
                    </li>
                    <li class="nav-item {{ Request::is('admin/room*') ? 'active':'' }}">
                        <a href="{{ route('admin.room.index') }}" class="nav-link nav-toggle"> <i class="fa fa-university" aria-hidden="true"></i>
                            <span class="title">Rooms</span>
                        </a>
                    </li>
                    <li class="nav-item {{ Request::is('admin/facilities*') ? 'active':'' }}">
                        <a href="{{ route('admin.facilities.index') }}" class="nav-link nav-toggle"> <i class="fa fa-diamond" aria-hidden="true"></i>
                            <span class="title">Facilities</span>
                        </a>
                    </li>
                    <li class="nav-item {{ Request::is('admin/booking*') ? 'active':'' }}">
                        <a href="{{ route('admin.booking.index') }}" class="nav-link nav-toggle"> <i class="fa fa-calendar" aria-hidden="true"></i>
                            <span class="title">Booking</span>
                        </a>
                    </li>

                    @elseif(Request::is('owner*'))
                        <li class="nav-item ">
                            <a href="{{ route('home') }}" class="nav-link nav-toggle"> <i class="material-icons">home</i>
                                <span class="title">Back to Home</span>
                            </a>
                        </li>
                        <li class="nav-item {{ Request::is('owner/dashboard') ? 'active':'' }}">
                            <a href="{{ route('owner.dashboard') }}" class="nav-link nav-toggle"> <i class="material-icons">dashboard</i>
                                <span class="title">Dashboard</span>
                            </a>
                        </li>
                    <li class="nav-item {{ Request::is('owner/room*') ? 'active':'' }}">
                        <a href="{{ route('owner.room.index') }}" class="nav-link nav-toggle"> <i class="fa fa-university" aria-hidden="true"></i>
                            <span class="title">Rooms</span>
                        </a>
                    </li>

                    @else
                        <li class="nav-item ">
                            <a href="{{ route('home') }}" class="nav-link nav-toggle"> <i class="material-icons">home</i>
                                <span class="title">Back to Home</span>
                            </a>
                        </li>

                    @endif
            </ul>
        </div>
    </div>
</div>
<!-- end sidebar menu -->