routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/search','HomeController@searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@autocomplete')->name('autocomplete');
// Hotel
Route::get('/all-hotel','HomeController@all_hotel')->name('hotel');
// Hotel Details
Route::get('/hotel/{id}/{slug}','HomeController@hotel')->name('hotel-details');
// Room
Route::get('/room/{id}/{slug}','HomeController@room')->name('room');
// Room Booking
Route::post('/room_booking','HomeController@roomBooking')->name('booking');
Route::post('/one-room-booking','HomeController@oneroomBooking')->name('one_booking');
// Admin Route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'admin','middleware' => ['auth','admin']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Owner
    Route::resource('owner','OwnerController');
    // Division
    Route::resource('division','DivisionController');
    // Zillas
    Route::resource('zilla','ZillaController');
    // Hotel
    Route::resource('hotel','HotelController');
    // Facilities
    Route::resource('facilities','FacilitiesController');

    Route::get('/district','HotelController@getDistrict');
   // Room
    Route::resource('room','RoomController');
    // Booking
    Route::resource('booking','BookingController');
    Route::get('/reject','BookingController@bookingReject')->name('booking.reject');



    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// Owner Route
Route::group(['as' =>'owner.','prefix'=>'owner','namespace'=>'owner','middleware' => ['auth','owner']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Room
    Route::resource('room','RoomController');
    Route::post('/room-free','RoomController@unbooking')->name('room-free');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// User Route
Route::group(['as' =>'user.','prefix'=>'user','namespace'=>'user','middleware' => ['auth','user']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});

resources/views/admin/dashboard.blade.php
@extends('layouts.backend.app')

@section('title','Admin-Dashboard')
@push('css')
    <!-- data tables -->
    <link href="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css"/>
    <!--sweetalert2 -->
    <link href="{{ asset('backend/assets/css/sweetalert2.min.css') }}" rel="stylesheet" type="text/css"/>
    {{--<link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">--}}
@endpush

@section('content')
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Dashboard</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{{ route('admin.dashboard') }}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                        </li>
                        <li class="active">Dashboard</li>
                    </ol>
                </div>
            </div>
            <!-- start widget -->
            <div class="state-overview">
                <div class="row">
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel deepPink-bgcolor">
                            <div class="symbol">
                                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value=" {{ $owners->count() }}">{{ $owners->count() }}</p>
                                <p>Hotel Owners</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel orange">
                            <div class="symbol">
                                <i class="fa fa-h-square" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value="{{ $hotels->count() }}">{{ $hotels->count() }}</p>
                                <p>Hotels</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel deepPink-bgcolor">
                            <div class="symbol">
                                <i class="fa fa-university" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value="{{ $rooms->count() }}">{{ $rooms->count() }}
                                <p>Rooms </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel orange">
                            <div class="symbol">
                                <i class="fa fa-diamond" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value="{{ $facilities->count() }}">{{ $facilities->count() }}</p>
                                <p>Facilities</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel deepPink-bgcolor">
                            <div class="symbol">
                                <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value="{{ $complete_booking->count() }}">{{ $complete_booking->count() }}</p>
                                <p>Complete Booking</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-4">
                        <div class="overview-panel orange">
                            <div class="symbol">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                            </div>
                            <div class="value white">
                                <p class="sbold addr-font-h1" data-counter="counterup" data-value="{{ $pending_booking->count() }}">{{ $pending_booking->count() }}</p>
                                <p>New Booking</p>
                            </div>
                        </div>
                    </div>
                </div>




            </div>

        </div>
    </div>
@endsection

@push('js')
    <!-- counterup js -->
    <script src="{{ asset('backend/assets/plugins/counterup/jquery.waypoints.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/plugins/counterup/jquery.counterup.min.js') }}" ></script>

    <!-- data tables -->
    <script src="{{ asset('backend/assets/plugins/datatables/jquery.dataTables.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/js/pages/table/table_data.js') }}" ></script>
    <script src="{{ asset('https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.js') }}" ></script>


@endpush

resources/views/admin/profile.blade.php
@extends('layouts.backend.app')

@section('title','Profile')
@push('css')
    <!-- data tables -->
    <link href="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css"/>
    <!-- sweetalert2-->
    {{--<link href="{{ asset('assets/backend/css/sweetalert2.min.css') }}" rel="stylesheet" type="text/css"/>--}}
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">User Profile</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{{ route('admin.dashboard') }}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                        </li>
                        </li>
                        <li class="active">User Profile</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN PROFILE SIDEBAR -->
                    <div class="profile-sidebar offset-4">
                        <div class="card card-topline-aqua">
                            <div class="card-body no-padding height-9">
                                <div class="row">
                                    <div class="profile-userpic">
                                        <img src=" {{ asset('storage/profile/'.Auth::user()->image) }}" class="img-responsive" alt=""> </div>
                                </div>
                                <div class="profile-usertitle">
                                    <div class="profile-usertitle-name">{{ Auth::user()->name }} </div>
                                    <div class="profile-usertitle-job">{{ Auth::user()->role->role_name }} </div>
                                </div>
                                <div class="card-body no-padding height-9">
                                    <ul class="list-group list-group-unbordered">
                                        <table class="table">
                                            <tr>
                                                <td><b>Email :</b></td>
                                                <td>{{ Auth::user()->email }}</td>
                                            </tr>
                                            <tr>
                                                <td><b>Phone :</b></td>
                                                <td>+880{{ Auth::user()->phone }}</td>
                                            </tr>
                                        </table>
                                    </ul>

                                </div>
                                <!-- END SIDEBAR USER TITLE -->
                            </div>
                            <!-- END BEGIN PROFILE SIDEBAR -->
                        </div>
                    </div>
                    <!-- end page content -->
                </div>
                <!-- end page container -->
@endsection

            @push('js')
                <!-- data tables -->
                    <script src="{{ asset('backend/assets/plugins/datatables/jquery.dataTables.min.js') }}" ></script>
                    <script src="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js') }}" ></script>
                    <script src="{{ asset('backend/assets/js/pages/table/table_data.js') }}" ></script>
                    {{--<script src="{{ asset('https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.js') }}" ></script>--}}
                    <script src="{{ asset('backend/assets/js/sweetalert2.min.js') }}" ></script>
                    <script type="text/javascript">
                        function deletePost(id) {
                            swal({
                                title: 'Are you sure?',
                                text: "You won't be able to revert this!",
                                type: 'warning',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'Yes, delete it!',
                                cancelButtonText: 'No, cancel!',
                                confirmButtonClass: 'btn btn-success',
                                cancelButtonClass: 'btn btn-danger',
                                buttonsStyling: false,
                                reverseButtons: true
                            }).then((result) => {
                                if (result.value) {
                                    event.preventDefault();
                                    document.getElementById('delete-form-'+id).submit();
                                } else if (
                                    // Read more about handling dismissals
                                    result.dismiss === swal.DismissReason.cancel
                                ) {
                                    swal(
                                        'Cancelled',
                                        'Your data is safe :)',
                                        'error'
                                    )
                                }
                            })
                        }
                    </script>
    @endpush

resources/views/admin/profile_setting.blade.php
@extends('layouts.backend.app')

@section('title','Profile - Setting')
@push('css')

@endpush

@section('content')
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Profile Setting</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{{ route('admin.dashboard') }}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>

                    </li>
                    <li class="active">Profile Setting</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-sm-8 offset-2">
                <div class="panel tab-border card-box">
                    <header class="panel-heading panel-heading-gray custom-tab">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a href="#about-2" data-toggle="tab" class="active show">
                                    <i class="fa fa-user"></i> Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#contact-2" data-toggle="tab" class="">
                                    <i class="fa fa-cogs"></i> Change Password
                                </a>
                            </li>
                        </ul>
                    </header>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active show" id="about-2">
                                <form method="POST" action="{{ route('admin.profile.update',$profile->id) }}" enctype="multipart/form-data" class="form-horizontal">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Name</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="name" value="{{ $profile->name }}">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Phone</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" maxlength="10" name="phone" value="{{ $profile->phone }}">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Email</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" name="email" value="{{ $profile->email }}">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email" class="col-sm-3 control-label">Profile Image</label>
                                        <div class="col-sm-8">
                                            <input type="file" class="form-control" name="image" >
                                        </div>
                                    </div>
                                    {{--<div class="form-group row">--}}
                                        {{--<label for="body" class="col-sm-3 control-label">About</label>--}}
                                        {{--<div class="col-sm-8">--}}
                                            {{--<textarea name="about"  cols="30" rows="6" class="tinymce">--}}
                                                {{--{{ $profile->about }}--}}
					                        {{--</textarea>--}}
                                        {{--</div>--}}
                                    {{--</div>--}}

                                    <div class="form-group">
                                        <div class="offset-md-3 col-md-9">
                                            <button type="submit" class="btn btn-info m-r-20">Update</button>
                                            <button type="button" class="btn btn-default">Cancel</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="tab-pane" id="contact-2">
                                <form method="POST" action="{{ route('admin.password.update') }}" class="form-horizontal">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label for="old password" class="col-sm-3 control-label">Old Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="old_password" class="form-control" id="old password" placeholder="Enter your old password" >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="new password" class="col-sm-3 control-label">New Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="password" class="form-control" id="new password" placeholder="Enter your new password" >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="old password" class="col-sm-3 control-label">Confirm Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="password_confirmation" class="form-control" id="Confirmed password" placeholder="Enter your new password again" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="offset-md-3 col-md-9">
                                            <button type="submit" class="btn btn-info m-r-20">Update</button>
                                            <button type="button" class="btn btn-default">Cancel</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- tinymce -->
    <script src="{{ asset('backend/assets/plugins/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('backend/assets/plugins/tinymce/init-tinymce.js') }}"></script>
@endpush