routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/search','HomeController@searchKeyword')->name('search');
Route::get('/autocomplete', 'HomeController@autocomplete')->name('autocomplete');
// Hotel
Route::get('/all-hotel','HomeController@all_hotel')->name('hotel');
// Hotel Details
Route::get('/hotel/{id}/{slug}','HomeController@hotel')->name('hotel-details');
// Room
Route::get('/room/{id}/{slug}','HomeController@room')->name('room');
// Room Booking
Route::post('/room_booking','HomeController@roomBooking')->name('booking');
Route::post('/one-room-booking','HomeController@oneroomBooking')->name('one_booking');
// Admin Route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'admin','middleware' => ['auth','admin']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Owner
    Route::resource('owner','OwnerController');
    // Division
    Route::resource('division','DivisionController');
    // Zillas
    Route::resource('zilla','ZillaController');
    // Hotel
    Route::resource('hotel','HotelController');
    // Facilities
    Route::resource('facilities','FacilitiesController');

    Route::get('/district','HotelController@getDistrict');
   // Room
    Route::resource('room','RoomController');
    // Booking
    Route::resource('booking','BookingController');
    Route::get('/reject','BookingController@bookingReject')->name('booking.reject');



    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// Owner Route
Route::group(['as' =>'owner.','prefix'=>'owner','namespace'=>'owner','middleware' => ['auth','owner']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    // Room
    Route::resource('room','RoomController');
    Route::post('/room-free','RoomController@unbooking')->name('room-free');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});
// User Route
Route::group(['as' =>'user.','prefix'=>'user','namespace'=>'user','middleware' => ['auth','user']],function (){

    // Dashboard Route
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

    // Profile Route
    Route::get('profile','ProfileController@index')->name('profile.index');
    Route::get('view-profile/{id}','ProfileController@show')->name('profile.view');
    Route::put('update-profile','ProfileController@update')->name('profile.update');
    Route::put('change-password','ProfileController@passwordUpdate')->name('password.update');
});

app/Models/Owner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
    // Relationship with hotels
    public function hotels()
    {
        //return $this->belongsTo('App\Models\Hotel');
        return $this->hasMany('App\Models\Hotel');
    }
}

app/Http/Controllers/Admin/OwnerController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Owner;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class OwnerController extends Controller
{

    public function index()
    {
        $owners = User::where('role_id','2')->latest()->get();
        return view('admin.owner.index',compact('owners'));
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'phone' => 'required',
            'email' => 'required|string|email|max:255|unique:users',
        ]);


        $owner = new User();
        $owner->name    = $request->name;
        $owner->role_id = "2";
        $owner->phone   = $request->phone;
        $owner->email   = $request->email;
        $owner->status  = "1";
        $owner->password = bcrypt('123456');
        $owner->save();

        Toastr::success('Hotel Owner Added Successfully','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.owner.index');
    }


    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Owner  $owner
     * @return \Illuminate\Http\Response
     */
    public function edit(Owner $owner)
    {
        //
    }


    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'phone' => 'required',
            'email' => 'required|string|email|max:255',
        ]);

        $ownerid = $request->id;

        $owner =  User::where('id',$ownerid)->first();
        $owner->name    = $request->name;
        $owner->phone   = $request->phone;
        $owner->email   = $request->email;
        $owner->status  = $request->status;
        $owner->save();

        Toastr::success('Hotel Owner Successfully Update','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.owner.index');
    }


    public function destroy($id)
    {
        $owner = User::where('id',$id)->first();
        if($owner->image == "user.png"){
            $owner->delete();
            Toastr::success('Hotel Owner Successfully Deleted','Success',["positionClass"=>"toast-top-right"]);
            return redirect()->route('admin.owner.index');
        }
        else{
            if(Storage::disk('public')->exists('profile/'.$owner->image))
            {
                Storage::disk('public')->delete('profile/'.$owner->image);
            }
            $owner->delete();
            Toastr::success('Hotel Owner Successfully Deleted','Success',["positionClass"=>"toast-top-right"]);
            return redirect()->route('admin.owner.index');
        }
    }
}

app/Http/Controllers/Owner/DashboardController.php
<?php

namespace App\Http\Controllers\owner;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
       return view('owner.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Owner/ProfileController.php
<?php

namespace App\Http\Controllers\owner;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProfileController extends Controller
{

    public function index()
    {
        $user_id = Auth::user()->id;
        $profile = User::where('id',$user_id)->first();
        return view('owner.profile_setting',compact('profile'));
    }
    // View Profile
    public function show($id)
    {
        $posts = User::where('id',Auth::id())->get();
        return view('owner.profile',compact('posts'));
    }


    public function update(Request $request)
    {
        $this->validate($request,[
            'name'  => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'phone' => 'required|string|max:255',
            //'about' => 'required',
            'image' => 'image',
        ]);
        $user = User::findOrFail(Auth::id());

        $image = $request->file('image');
        if(isset($image))
        {
            //Make unique image name
            $currentDate =  Carbon::now()->toDateString();
            $imageName   = $currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            //Check Post Dir is exists
            if(!Storage::disk('public')->exists('profile'))
            {
                Storage::disk('public')->makeDirectory('profile');
            }
            //Delete old post Image
            if(Storage::disk('public')->exists('profile/'.$user->image))
            {
                Storage::disk('public')->delete('profile/'.$user->image);
            }
            // Resize image for post and upload
            $postImage = Image::make($image)->resize(250,250)->save('foo' . $image->getClientOriginalExtension());
            Storage::disk('public')->put('profile/'.$imageName,$postImage);
        }
        else{
            $imageName = $user->image;
        }
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->phone    = $request->phone;
        $user->image    = $imageName;
        //$user->about    = $request->about;
        $user->update();

        Toastr::success('Profile Successfully Updated','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('owner.profile.index');


    }
    // Update Password
    public function passwordUpdate(Request $request)
    {
        $this->validate($request,[
            'old_password'  => 'required',
            'password'      => 'required|confirmed',
        ]);

        $hashedPassword = Auth::user()->password;
        if(Hash::check($request->old_password,$hashedPassword))
        {
            if(!Hash::check($request->password,$hashedPassword))
            {
                $user = User::findOrFail(Auth::id());
                $user->password = Hash::make($request->password);
                $user->save();
                Toastr::info('Password Successfully Changed','Info',["positionClass"=>"toast-top-right"]);
                Auth::logout();
                return redirect()->back();
            }
            else{
                Toastr::error('New password cannot be the same as old password','Error',["positionClass"=>"toast-top-right"]);
                return redirect()->back();
            }
        }
        else{
            Toastr::error('Current password not match','Error',["positionClass"=>"toast-top-right"]);
            return redirect()->back();
        }
    }

}

app/Http/Controllers/Owner/RoomController.php
<?php

namespace App\Http\Controllers\owner;

use App\Models\Facilities;
use App\Models\Hotel;
use App\Models\Owner;
use App\Models\Room;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class RoomController extends Controller
{

    public function index()
    {
        $user_id    = Auth::user()->id;
        $hotel_id   = Hotel::where('user_id',$user_id)->first();
        $rooms      = Room::where('hotel_id',$hotel_id->id)->latest()->get();
        return view('owner.room.index',compact('rooms'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'room_name' => 'required|string',
            'room_size' => 'required',
            'sleeps'    => 'required',
            'booking_price' => 'required',
            'qty'           => 'required',
        ]);
        $hotel          = $request->hotel_name;
        $owner          = Hotel::where('id',$hotel)->first();
        $name           = $request->room_name;
        $size           = $request->room_size;
        $sleep          = $request->sleeps;
        $price          = $request->booking_price;
        $sale_price     = $request->booking_sale_price;
        $qty            = $request->qty;
        $booking_status = $request->booking_status;
        $is_featured    = $request->is_featured;

        $id= DB::table('rooms')->insertGetId(
            array(
            'hotel_id'      => $hotel,
            'user_id'       => $owner->id,
            'room_name'     => $name,
            'room_size'     =>$size,
            'sleep'         =>$sleep,
            'qty'           =>$qty,
            'booking_price' =>$price,
            'booking_sale_price' =>$sale_price,
            'booking_status' =>$booking_status,
            'is_featured'   =>$is_featured
        ));
        // Insert Image
        $files = $request->file('files');
        foreach ($files as $file)
        {
        //$tmp_image = $file->getClientOriginalName();

        // Make Slug
        if(isset($file))
        {
            // Make Unique name
            $currentDate = Carbon::now()->toDateString();
            $image = $currentDate.'-'.uniqid().'.'.$file->getClientOriginalExtension();
            // Check dir exists
            if(!Storage::disk('public')->exists('room'))
            {
                Storage::disk('public')->makeDirectory('room');
            }
            // Resize Image
            $hotelImage = Image::make($file)->resize(1200,900)->save('foo'.$file->getClientOriginalExtension());
            Storage::disk('public')->put('room/'.$image,$hotelImage);
        }
        else{
            $image = "hotel.png";
        }

            DB::table('room_image')->insert(array(
                'room_id' => $id,
                'image'   => $image
            ));
        }
        // Insert Facilities
        $facilities = $request->facilities;
        foreach ($facilities as $facility)
        {
             DB::table('room_facilities')->insert(array(
                'room_id' => $id,
                'facilities_id'   => $facility
            ));
        }

        Toastr::success('Room Successfully Added','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.room.index');
    }
    // Hotel unbooking
    public function unbooking(Request $request)
    {
        $room_id =$request->room_id;
        $room = Room::where('id',$room_id)->first();
        $room->booking_status   = "0";
        $room->booking_start    = NULL;
        $room->booking_end      = NULL;
        $room->save();
        Toastr::success('Room Unbooking Success','Success');
        return redirect()->back();
    }
    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        $r_id = $request->id;
        $check_in = $request->check_in;
        $check_out = $request->check_out;
        $room = Room::where('id',$r_id)->first();
        $room->booking_start    = $check_in;
        $room->booking_end      = $check_out;
        $room->booking_status   = "1";
        $room->save();
        Toastr::success('Room Boooking Success ','Succcess');
        return redirect()->back();
    }

    public function destroy($id)
    {
        $room = Room::where('id',$id)->first();
        $roomImages = DB::table('room_image')->where('room_id',$room->id)->get();

        foreach($roomImages as $image)
        {
            if(Storage::disk('public')->exists('room/'.$image->image))
            {
                Storage::disk('public')->delete('room/'.$image->image);
            }
        }

        $room->delete();
        Toastr::success('Room Successfully Deleted','Success',["positionClass"=>"toast-top-right"]);
        return redirect()->route('admin.room.index');

    }

}

resources/views/owner/dashboard.blade.php
@extends('layouts.backend.app')

@section('title','Hotel Owner-Dashboard')
@push('css')
    <!-- data tables -->
    <link href="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css"/>
    <!--sweetalert2 -->
    <link href="{{ asset('backend/assets/css/sweetalert2.min.css') }}" rel="stylesheet" type="text/css"/>
    {{--<link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">--}}
@endpush

@section('content')

@endsection

@push('js')
    <!-- counterup js -->
    <script src="{{ asset('backend/assets/plugins/counterup/jquery.waypoints.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/plugins/counterup/jquery.counterup.min.js') }}" ></script>

    <!-- data tables -->
    <script src="{{ asset('backend/assets/plugins/datatables/jquery.dataTables.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js') }}" ></script>
    <script src="{{ asset('backend/assets/js/pages/table/table_data.js') }}" ></script>
    <script src="{{ asset('https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.js') }}" ></script>

    <script type="text/javascript">
        function deletePost(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>

@endpush

resources/views/owner/profile_setting.blade.php
@extends('layouts.backend.app')

@section('title','Profile - Setting')
@push('css')

@endpush

@section('content')
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Profile Setting</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{{ route('owner.dashboard') }}">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>

                    </li>
                    <li class="active">Profile Setting</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-sm-8 offset-2">
                <div class="panel tab-border card-box">
                    <header class="panel-heading panel-heading-gray custom-tab">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a href="#about-2" data-toggle="tab" class="active show">
                                    <i class="fa fa-user"></i> Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#contact-2" data-toggle="tab" class="">
                                    <i class="fa fa-cogs"></i> Change Password
                                </a>
                            </li>
                        </ul>
                    </header>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active show" id="about-2">
                                <form method="POST" action="{{ route('owner.profile.update',$profile->id) }}" enctype="multipart/form-data" class="form-horizontal">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Name</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="name" value="{{ $profile->name }}">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Phone</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" maxlength="10" name="phone" value="{{ $profile->phone }}">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 control-label">Email</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" name="email" value="{{ $profile->email }}">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email" class="col-sm-3 control-label">Profile Image</label>
                                        <div class="col-sm-8">
                                            <input type="file" class="form-control" name="image" >
                                        </div>
                                    </div>
                                    {{--<div class="form-group row">--}}
                                        {{--<label for="body" class="col-sm-3 control-label">About</label>--}}
                                        {{--<div class="col-sm-8">--}}
                                            {{--<textarea name="about"  cols="30" rows="6" class="tinymce">--}}
                                                {{--{{ $profile->about }}--}}
					                        {{--</textarea>--}}
                                        {{--</div>--}}
                                    {{--</div>--}}

                                    <div class="form-group">
                                        <div class="offset-md-3 col-md-9">
                                            <button type="submit" class="btn btn-info m-r-20">Update</button>
                                            <button type="button" class="btn btn-default">Cancel</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="tab-pane" id="contact-2">
                                <form method="POST" action="{{ route('owner.password.update') }}" class="form-horizontal">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label for="old password" class="col-sm-3 control-label">Old Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="old_password" class="form-control" id="old password" placeholder="Enter your old password" >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="new password" class="col-sm-3 control-label">New Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="password" class="form-control" id="new password" placeholder="Enter your new password" >
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="old password" class="col-sm-3 control-label">Confirm Password</label>
                                        <div class="col-sm-8">
                                            <input type="password" name="password_confirmation" class="form-control" id="Confirmed password" placeholder="Enter your new password again" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="offset-md-3 col-md-9">
                                            <button type="submit" class="btn btn-info m-r-20">Update</button>
                                            <button type="button" class="btn btn-default">Cancel</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- tinymce -->
    {{--<script src="{{ asset('backend/assets/plugins/tinymce/tinymce.min.js') }}"></script>--}}
    {{--<script src="{{ asset('backend/assets/plugins/tinymce/init-tinymce.js') }}"></script>--}}
@endpush